### PR TITLE
color bubbles

### PR DESCRIPTION
**Pull request by tom-mohr**
changed color selection to dropdown menu with bubbles

### CODE REVIEW

**Review by Gegd99 — CHANGES_REQUESTED** [review]
If you have the keyboard open and press on the color bubbles they move to much up. Closing the keyboard, when choosing the color could be fine.

**Comment by Gegd99** [comment]
Other possible solution could be to make them smaller and/or display them horizontally under the title, instead of vertically.

**Comment by tom-mohr** [comment]
I can't reproduce that. Maybe my screen is too large? Can you provide a more detailed description of the issue?

**Review by Gegd99 — APPROVED** [review]
Really nice

**Pull request merged**
